#DB_USERNAME: istadlms
#DB_PASSWORD: ISTAD@LMS
#DB_HOST: 152.42.220.220
#DB_PORT: 5433
#DB_NAME: istad_lms_db
#
#ACT_PRIVATE: access-refresh-token-keys/access-token-private.key
#ACT_PUBLIC: access-refresh-token-keys/access-token-public.key
## This is for the refresh token
#RET_PRIVATE: access-refresh-token-keys/refresh-token-private.key
#RET_PUBLIC: access-refresh-token-keys/refresh-token-public.key

SERVER_PORT: 8888

MAIL_USERNAME: sokname56@gmail.com
MAIL_PASSWORD: ehis ldbm otct hykc
MAIL_HOST: smtp.gmail.com
MAIL_HOST_PORT: 587

SECURITY_NAME: soknem
SECURITY_PASSWORD: 12345

MINIO_URL: http://152.42.220.220:9000
MINIO_ACCESS_KEY: kWe6XgiJA2AYKT5UhYCE
MINIO_SECRETE_KEY: NPj7pt3Q2lIHH7c1ytUZS3hr2ZOSudpmNB4rCaf6
MINIO_BUCKET: minio-test-bucket-1

MEDIA_SERVER_PATH: D:\\SERVER\\ITE\\
MEDIA_BASE_URI: http://localhost:8080/media/

